### ISSUE TITLE
Hoffstadt Initial Tasks

### ISSUE THREAD

**Issue by hoffstadt** [hoffstadt/pilotlight-ui#1]
## Background
No reason to make issues at the moment when its mostly just Cothren & myself. I'm also tired of sticky notes on my desk. This will be my running list of notes and things for me to do.

## Tasks & Notes

- [ ] cleanup ui files (messy after separating into standalone library for this repo)
- [ ] cleanup example files
- [ ] cleanup backend files
- [ ] add DirectX 11 backend (also a good way to ensure C++ compatibility)
- [ ] handle naming conflicts with pilotlight-libs (stretchy buffer macros)
- [ ] cleanup stb_textedit inclusion
- [ ] ensure stb libs don't interfere with engine stb libs
- [ ] ensure uniform naming conventions
- [ ] move as much unstable api to pl_ui_internal.h
- [ ] decide on a possible rename for this library
- [ ] test everything in pilotlight engine
